# Generated by Django 5.1.2 on 2025-03-08 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='cards.cardfile'),
        ),
        migrations.AddField(
            model_name='cardrequest',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card'),
        ),
        migrations.AddField(
            model_name='cardrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='requests',
            field=models.ManyToManyField(through='cards.CardRequest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cardrequest',
            constraint=models.UniqueConstraint(fields=('requested_by', 'card'), name='unique_card_request'),
        ),
    ]
