# Generated by Django 5.1.2 on 2025-03-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebaseuser',
            name='phone_number',
        ),
    ]
